
<!--   ******************************************************************************
       * footer.inc                                                      02/27/2009 *
       * For www.myblackjeep.com by Mark Coulter                                    *
       * Footer information.                                                        *
       *                                                                            *
       * Modified - 03/02/2009 - MDC                                                *
       *   Changed comment block. Hid it inside PHP code tag.                       *
       *                                                                            *
       * Modified - 03/09/2009 - MDC                                                *
       *   Changed the comment block back to html comment. That way the PHP         *
       *   processor doesn't have to parse it. For a site as small as this one      *
       *   it doesn't make a difference.                                            *
       *                                                                            *
       * Modified - 10/21/2009 - MDC                                                *
       *   Cleaned up root directory for the website. Arranged files into           *
       *   directories and renamed some of the directories.                         *
       *                                                                            *
       *                                                                            *
       *                                                                            *
       *                                                                            *
       *                                                                            *
       ****************************************************************************** -->
        <div id="footer">
            <p>Copyright &copy; 2009 Mark Coulter</p>
        </div>
<!-- end of footer.inc -->