<!--   ******************************************************************************
       * lightboxscripts.inc                                             10/22/2009 *
       * For www.myblackjeep.com by Mark Coulter                                    *
       *                                                                            *
       *                                                                            *
       *                                                                            *
       *                                                                            *
       ****************************************************************************** -->
<script type="text/javascript" src="/js/prototype.js"></script>
<script type="text/javascript" src="/js/scriptaculous.js?load=effects,builder"></script>
<script type="text/javascript" src="/js/lightbox.js"></script>
<link rel="stylesheet" href="/css/lightbox.css" type="text/css" media="screen" />
<!-- end of lightboxscripts.inc -->